Repository patrickmonteiro/quasar-apexcharts, pull requests merged in 2020-10, with the labels that each got.

#9 Exibir marcadores no gráfico tipo RADAR
  LICENSE.md
  README.md
  src/components/ApexRadar.vue
Labels: feature

#11 7_add_polarmap: Adicionar o gráfico polar map
  src/components/ApexPolarMap.vue
  src/pages/Dashboard.vue
Labels: feature

#12 Adicionar gráfico treemap
  src/components/ApexTreemap.vue
  src/pages/Dashboard.vue
Labels: feature, hacktoberfest-accepted

#14 Adicionar gráfico misto Line & Column
  src/components/ApexLineColumn.vue
  src/pages/Dashboard.vue
Labels: feature, hacktoberfest-accepted

#13 Adicionar gráfico misto Line e Scatter
  src/components/ApexLineScatter.vue
  src/pages/Dashboard.vue
Labels: feature, hacktoberfest-accepted

#15 Add Area Chart & Some changes
  src/components/ApexArea.vue
  src/components/ApexBubble.vue
  src/components/ApexColumn.vue
  src/components/ApexDonut.vue
  src/components/ApexHeatmap.vue
  src/components/ApexLine.vue
  src/components/ApexMultipleRadialBars.vue
  src/components/ApexPolarMap.vue
  src/components/ApexRadialBar.vue
  src/pages/Dashboard.vue
Labels: hacktoberfest-accepted
